export const GAME_LOOP_INTERVAL = 1000 / 60;
export const MAX_PLAYER_SPEED = 2;
export const PLAYER_MIN_ATTACK_DISTANCE = 32;

export const PLAYER_CHANCE_TO_HIT_FACTOR = 0.5;
export const PLAYER_CHANCE_TO_HIT_MIN = 0.1;
export const PLAYER_CHANCE_TO_HIT_MAX = 0.9;
export const PLAYER_HIT_RATIO_FACTOR = 1.2;
export const PLAYER_DAMAGE_BONUS_FACTOR = 0.2;